create table serial_numbers (
    serial_number       text not null,
    organization_id     int not null,
    item_id             int not null,
    complection_date    text,
    current_status      text,
    manufactor          text,
    params              text
);

create table serial_numbers_tmp (
    serial_number        text not null,
    organization_id      int not null,
    item_id              int not null,
    complection_date     text,
    current_status       text,
    manufactor           text,
    params               text
);

alter table shipment add column sn_ctrl text;
alter table shipment_tmp add column sn_ctrl text;

alter table shipment_dso add column sn_ctrl text;
alter table shipment_dso_tmp add column sn_ctrl text;

alter table shipment add column serial_number text;
alter table shipment_tmp add column serial_number text;

alter table shipment_dso add column serial_number text;
alter table shipment_dso_tmp add column serial_number text;

create table receive_list_new (
    _id integer primary key autoincrement,
    item_code text,
    item_descr text,
    uom_code text,
    all_qty real,
    rec_qty real,
    rest_qty real,
    order_number text,
    vendor text,
    shipment_number text,
    rcv_transaction_id integer,
    po_distribution_id integer,
    recipient text,
    project text,
    task text,
    due_date text,
    packing_slip text,
    unit_price real,
    currency_code text,
    sn_ctrl text,
    sn_prefix text,
    sn_first_number text,
    serial_number text,
    lot_ctrl text,
    lot_prefix text,
    lot_first_num text,
    shelf_life_code text,
    is_metals text,
    lot_number text,
    expiration_date text,
    module text,
    metal_unit text,
    au real,
    ag real,
    pt real,
    pt_gr real,
    pd real,
    rh real,
    ru real,
    comment text,
    term_of_receipt text,
    currency_conv_date text,
    docs text,
    docs_checked text,
    need_inspection text,
    item_id integer not null,
    organization_id int,
    move_mark text not null default 'N',
    subinventory text,
    whse text not null,
    ryad text,
    cell text
);

insert into receive_list_new(
    item_code,
    item_descr,
    uom_code,
    all_qty,
    rec_qty,
    rest_qty,
    order_number,
    vendor,
    shipment_number,
    rcv_transaction_id,
    po_distribution_id,
    recipient,
    project,
    task,
    due_date,
    packing_slip,
    unit_price,
    currency_code,
    sn_ctrl,
    sn_prefix,
    sn_first_number,
    serial_number,
    lot_ctrl,
    lot_prefix,
    sn_first_number,
    shelf_life_code,
    is_metals,
    lot_number,
    expiration_date,
    module,
    metal_unit,
    au,
    ag,
    pt,
    pt_gr,
    pd,
    rh,
    ru,
    comment,
    term_of_receipt,
    currency_conv_date,
    docs,
    docs_checked,
    need_inspection,
    item_id,
    organization_id,
    move_mark,
    subinventory,
    whse,
    ryad,
    cell)
select item_code,
    item_descr,
    uom_code,
    all_qty,
    rec_qty,
    rest_qty,
    order_number,
    vendor,
    po_shipment_number,
    rcv_transaction_id,
    po_distribution_id,
    recipient,
    project,
    task,
    due_date,
    packing_slip,
    unit_price,
    currency,
    sn_ctrl,
    sn_prefix,
    sn_first_num,
    SerialNum,
    lot_ctrl,
    lot_prefix,
    lot_first_num,
    shelf_life_code,
    is_metals,
    lot_number,
    expiration_date,
    module,
    metal_unit,
    cast( Au as real),
    cast( Ag as real),
    cast( Pt as real),
    cast( PtGr as real),
    cast( Pd as real),
    cast( Rh as real),
    cast( Ru as real),
    description,
    term_of_receipt,
    currency_conv_date,
    docs,
    docs_checked,
    need_inspection,
    item_id,
    organization_id,
    ifnull(move_mark, 'N'),
    subinventory,
    whse,
    location,
    cell from receive_list;

drop table receive_list;

alter table receive_list_new rename to receive_list;

drop table receive_list_tmp;

create table receive_list_tmp(
    _id integer primary key autoincrement,
    item_code text,
    item_descr text,
    uom_code text,
    all_qty real,
    rec_qty real,
    rest_qty real,
    order_number text,
    vendor text,
    shipment_number text,
    rcv_transaction_id integer,
    po_distribution_id integer,
    recipient text,
    project text,
    task text,
    due_date text,
    packing_slip text,
    unit_price real,
    currency_code text,
    sn_ctrl text,
    sn_prefix text,
    sn_first_number text,
    serial_number text,
    lot_ctrl text,
    lot_prefix text,
    lot_first_num text,
    shelf_life_code text,
    is_metals text,
    lot_number text,
    expiration_date text,
    module text,
    metal_unit text,
    au real,
    ag real,
    pt real,
    pt_gr real,
    pd real,
    rh real,
    ru real,
    comment text,
    term_of_receipt text,
    currency_conv_date text,
    docs text,
    docs_checked text,
    need_inspection text,
    item_id integer not null,
    organization_id int,
    move_mark text not null default 'N',
    subinventory text,
    whse text not null,
    ryad text,
    cell text
);

create table wait_receive_list_new(
    _id integer primary key autoincrement,
    item_code text not null,
    item_descr text,
    uom_code text not null,
    fact_rec_qty real not null,
    free_qty real not null,
    move_qty real,
    free_with_pers_qty real,
    perc_extra text,
    unit_price real,
    order_number text,
    vendor text,
    receiver text,
    po_shipment_number text,
    project text,
    task text,
    expected_receipt_date text,
    currency_code text,
    rate_type text,
    rate_date text,
    rate_val real,
    need_inspection text,
    po_location text not null,
    line_location_id integer not null,
    packing_slip text,
    term_of_receipt text,
    docs text,
    docs_checked text,
    lot_number text,
    module text,
    metal_unit text,
    au real,
    ag real,
    pt real,
    pt_gr real,
    pd real,
    rh real,
    ru real,
    serial_number text,
    sn_ctrl text,
    sn_prefix text,
    sn_first_number text,
    lot_ctrl text,
    lot_prefix text,
    lot_first_num text,
    shelf_life_code text,
    is_metals text,
    shipment_header_id integer not null,
    shipment_line_id integer not null,
    acc text,
    item_id integer not null,
    comment text,
    organization_id int not null,
    expiration_date text,
    move_mark text not null default 'N',
    subinventory text,
    whse text not null,
    ryad text,
    cell text
);

insert into wait_receive_list_new(
    item_code,
    item_descr,
    uom_code,
    fact_rec_qty,
    free_qty,
    move_qty,
    free_with_pers_qty,
    perc_extra,
    unit_price,
    order_number,
    vendor,
    receiver,
    po_shipment_number,
    project,
    task,
    expected_receipt_date,
    currency_code,
    rate_type,
    rate_date,
    rate_val,
    need_inspection,
    po_location,
    line_location_id,
    packing_slip,
    term_of_receipt,
    docs,
    docs_checked,
    lot_number,
    module,
    metal_unit,
    au,
    ag,
    pt,
    pt_gr,
    pd,
    rh,
    ru,
    serial_number,
    sn_ctrl,
    sn_prefix,
    sn_first_number,
    lot_ctrl,
    lot_prefix,
    lot_first_num,
    shelf_life_code,
    is_metals,
    shipment_header_id,
    shipment_line_id,
    acc,
    item_id,
    comment,
    organization_id,
    expiration_date,
    move_mark,
    subinventory,
    whse,
    ryad,
    cell)
select item_code,
    item_descr,
    uom_code,
    fact_rec_qty,
    free_qty,
    move_qty,
    free_with_pers_qty,
    perc_extra,
    cast(unit_price as real),
    order_number,
    vendor,
    receiver,
    po_shipment_number,
    project,
    task,
    expected_receipt_date,
    currency_code,
    rate_type,
    rate_date,
    rate_val,
    po_need_inspection,
    po_location,
    line_location_id,
    packing_slip,
    term_of_receipt,
    docs,
    docs_checked,
    lot_number,
    module,
    metal_unit,
    cast( Au as real),
    cast( Ag as real),
    cast( Pt as real),
    cast( PtGr as real),
    cast( Pd as real),
    cast( Rh as real),
    cast( Ru as real),
    SerialNum,
    sn_ctrl,
    sn_prefix,
    sn_first_num,
    lot_ctrl,
    lot_prefix,
    lot_first_num,
    shelf_life_code,
    is_metals,
    shipment_header_id,
    shipment_line_id,
    acc,
    item_id,
    description,
    organization_id,
    expiration_date,
    move_mark,
    subinventory,
    whse,
    location,
    cell from wait_receive_list;

drop table wait_receive_list;

alter table wait_receive_list_new rename to wait_receive_list;

drop table wait_receive_list_tmp;

create table wait_receive_list_tmp(
    _id integer primary key autoincrement,
    item_code text not null,
    item_descr text,
    uom_code text not null,
    fact_rec_qty real not null,
    free_qty real not null,
    move_qty real,
    free_with_pers_qty real,
    perc_extra text,
    unit_price real,
    order_number text,
    vendor text,
    receiver text,
    po_shipment_number text,
    project text,
    task text,
    expected_receipt_date text,
    currency_code text,
    rate_type text,
    rate_date text,
    rate_val real,
    need_inspection text,
    po_location text not null,
    line_location_id integer not null,
    packing_slip text,
    term_of_receipt text,
    docs text,
    docs_checked text,
    lot_number text,
    module text,
    metal_unit text,
    au real,
    ag real,
    pt real,
    pt_gr real,
    pd real,
    rh real,
    ru real,
    serial_number text,
    sn_ctrl text,
    sn_prefix text,
    sn_first_number text,
    lot_ctrl text,
    lot_prefix text,
    lot_first_num text,
    shelf_life_code text,
    is_metals text,
    shipment_header_id integer not null,
    shipment_line_id integer not null,
    acc text,
    item_id integer not null,
    comment text,
    organization_id int not null,
    expiration_date text,
    move_mark text not null default 'N',
    subinventory text,
    whse text not null,
    ryad text,
    cell text
);